language: php

php:
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4

script:
  - make dev
  - make test
  - make prod
  - make build
  - make reset

deploy:
  provider: releases
  api_key:
    secure: hZvt8D4qE/gob4D/uJPE5TDihGqHxsQ5AQE6pwL9MviznFT8751bZFWtw2HCL0qVDSEY4xjPX+1TxvUPK9xyDOA+Z9poj9zzdJCtVqR9Wmcruz6ILUVV8/vPjmLHbOr59rjhuNKZwfLtdGUII6D78dfv1n8brucFUqCARsgCGxYBBV8VxEWECVwjzBRXwETfBQ0EO4N79aDIy5JTQMNM3nAmij5pyq1KF2YdFrJjCkzZTnu6nkXeK8Ii4ucJ3rl6jIJTurA6T0h+M6YgTuyrYb8TNMsyZ1MmTJcji2LOZnOS/Jxagh8hUCHy4svIJdMDb88Zfy3K3H4OhGcyUtUv5Jt4J2bvG/femEkw9e0+rg02FMkSw4KXYftgvLq0OX6v8XioHtxGH6jqg2ucp8J7LJlYiaGeTAkShJZ04nhI7wD0uMPEL8QKmoFOkW8QJ7k26FbOSDGCkIhu6FpigAm+UNDjNgJ0IELJ4dvDDhXv6wxk7Q1iOM6ZPuLXQde0xbL/BGGQPN1PnUHojT7jY/tBKttjhuAKtuEQ/NU3NgGcnlO63TnVkP51RoqqP64x2mpT9SUE5ooWcRnEvBfUuV/IH7Af4wSRBMiy3LY7H4vzWa+5MAohqdayd1ZIRoE8epXzt+cb2n7wRsA4vWb/EAT7gRvwSOLLRqrXpB3LEbDeBTs=
  file:
    - "./build/jbzoo_clean_install.zip"
    - "./build/jbzoo_update.zip"
  on:
    repo: JBZoo-CCK/JBZoo
  skip_cleanup: 'true'
